<?xml version="1.0" encoding="UTF-8"?><record_update>
    <sys_documentation element="database_instance_reference" label="Data Source Instance Reference" language="en" table="x_ibmrt_guard_test_exception">
        <sys_documentation action="INSERT_OR_UPDATE">
            <element>database_instance_reference</element>
            <help/>
            <hint/>
            <label>Data Source Instance Reference</label>
            <language>en</language>
            <name>x_ibmrt_guard_test_exception</name>
            <plural>Data Source Instance References</plural>
            <sys_class_name>sys_documentation</sys_class_name>
            <sys_created_by>admin</sys_created_by>
            <sys_created_on>2022-01-21 21:19:33</sys_created_on>
            <sys_id>062958b51b374d50489ceb522a4bcbd4</sys_id>
            <sys_mod_count>2</sys_mod_count>
            <sys_name>Data Source Instance Reference</sys_name>
            <sys_package display_value="IBM Guardium Vulnerability Assessment" source="x_ibmrt_guard">912d85fd87940110387c64280cbb35dc</sys_package>
            <sys_policy/>
            <sys_scope display_value="IBM Guardium Vulnerability Assessment">912d85fd87940110387c64280cbb35dc</sys_scope>
            <sys_update_name>sys_documentation_x_ibmrt_guard_test_exception_database_instance_reference_en</sys_update_name>
            <sys_updated_by>admin</sys_updated_by>
            <sys_updated_on>2022-04-29 12:25:38</sys_updated_on>
            <url/>
            <url_target/>
        </sys_documentation>
    </sys_documentation>
</record_update>
